scripts/promiseOghenevwefe.js
Promise Oghenevwefe Task 2 submission
=> Added Promise Oghenevwefe Task 2

scripts/Adakole-James.php
=> Scripts added

scripts/vasanth.py
=> team incredible task - Vasanth9

scripts/fidele-kirezi-cyisa.py
=> my codes Team-Increadible

.gitignore, scripts/Eleam.py
Clean up done on the folder structure using thr .gitignore file, this
helps prevent folders that are not necessarily supported by the project
and should be updated frequently
Also, submitting my script as required
=> chore: Adding my file and necessary clean up

scripts/Daniel-Olatoye.py
=> daniel-olatoye.py

scripts/Ibrahim-Adekunle.js
Ibrahim Adekunle Script Submission
=> Ibrahim-Adekunle script

scripts/Amarachi-Erem.py, scripts/random_AmarachiErem.py
Written my code according to the format
=> Updated my name

scripts/Yahaya-Yohanna.js
=> Yahaya Yohanna's Script

scripts/awa-felix.dart
The code runs locally and passes the test. Yes I checked!
=> awafelix task

scripts/Kubiat-Morgan.js
**What's in this PR?**
- Added `Kubiat-Morgan.js` file to `scripts` folder
=> Feat(*): add own js script

scripts/Adebayo-Pelumi.js
=> Initial commit of Pelumi Adebayo for stage 2 task

scripts/Tobechi-Chukwuleta.py
Hey Guys, here is my task for team incredible, please merge.
Thanks,
Tobechi
=> Tobechi-Chukwuleta.py task for team incredible

scripts/Muyiwa-Adebayo.js
Merge: Muyiwa-Adebayo.js with the required detail for the team task
=> Muyiwa-Adebayo.js

scripts/Olusegun-Olalere.js
Team Incredible task completed.
=> Olusegun-Olalere script

scripts/ArinzeAlekeHNGTask2.php
Team Incredible task using PHP
=> ArinzeAleke(emmanuelaleke.gmail.com)

scripts/Chimdia-Anyiam.js
I added my script to the scripts folder
=> added my script

scripts/Adedeji-Abiola.js
Script has passed test on my machine
=> script for Adedeji Abiola

scripts/David-Ajibade.js
Task completed using JavaScript
=> Task  2 task completed

scripts/agharayee.js
=> added MyScript

scripts/petrepan.js
=> incredible pr

scripts/Bashiru-Akintayo.py
=> Add Bashiru-Akintayo Script

scripts/raji-sarafadeen.js
=> task 2 commit

scripts/Chidubem-Nwankwo.php
script tested on local machine, kindly merge
=> Chidubem-Nwankwo.php

scripts/Joshua-Oke.js
I used a branch instead of master. I hope that is fine
=> create Joshua-Oke.js for teamIncredible task

scripts/Adebayo-Pelumi.js
=> Added full stop to my string

index.php
just change the leads to the latest choose by the room
=>  Updated Leaders name

scripts/RolandJethro-Suyom.js
I added RolandJethro-Suyom.js with my info. Thanks!
=> Submitting for the task 

scripts/Timfon-Ekott.js
This PR adds my script to the project.
=> added Tim script

scripts/oghenekome-akaka.js
Done
For any feedback, please reach me on Slack via @kome
=> my script for team-incredible task

scripts/Odiri-Ighogboja.js
Odizee's new pull request. Kindly accept.
=> Odiri_Ighogboja_FIle

scripts/Augusta-Ehihebolo.js
=> AugustaEhihebolo commit

scripts/Jumoke-Olaleye.php
=> Jumoke olaleye

scripts/Angel-Nagaba.js
Hello,
Here is my task for the team incredible. Any reviews are welcome.
slack username @Angel 
Thank you
=> My script for the team incredible task

.vscode/settings.json, scripts/Israel-Airenovboise.py
added some things to make it more unique
=> my python script.

scripts/Christian-Ndu.js
=> my submission

scripts/Abdulrahman-Olagunju.js
=> Add BodeRahman script

scripts/Abeid-Juma.php
added abeid-juma.php on the script folder
=> added abeid.php script

scripts/Abdullahi-Idris.js
Initial Commit for HNG-03730, Abdullahi Idris
=> Initial Commit for HNG-03730

scripts/Babatunde-Adenowo.php
xodeeq on Slack, Team Incredible Task 2
=> PHP file added by Babatunde Adenowo

scripts/Abdulateef-Gafar.py
=> first commit to the incredibles by Gafar_01

scripts/ohis-ohiorenoya.js
I have tested my file and it works fine
=> chore: create script

scripts/Samuel-Omilo.js
Add my script for team incredible
=> add @milz 's script

scripts/Blessing-Akpan.js
=> Blessing-Akpan.js

scripts/Onyekachukwu-Odenigbo.py
=>  Onyekachukwu-Odenigbo.py

scripts/semiu-biliaminu.php
=> added my detail

scripts/Ogidan-sadiat.js
=> add ogidansadiat script

scripts/Kelvin-Oigiangbe.js
=> my added script

scripts/blessed_madukoma06453.php
Reverts elishaukpong/Team-Incredible#149
=> Revert "my commit: blessed_madukoma.php"

scripts/Seye-Olofinyo.js
=> team-incredible task

scripts/Dev-Quie.php
My first contribution to team-incredible. Kindly merge.
=> Devquie's script

README.md
This is an edit to the readme on supported languages and file format
=> Could help

scripts/Jeffrey-Asamoah-Ojugbana.js
=> Asamoah-Ojugbana Jeffrey HNGi7-01117

scripts/Aderonke-Odushola.js
Pull request for team incredible.
=> ronnycrown-HNG-00477 script for team incredible

scripts/justin-edechukwu.js
=> first commit

scripts/Blessing-Uduose.py
All guidelines have been followed.
=> Blessing-Uduose Team-Incredible

scripts/David-Adeyemi.js
-Made with Javascript
-By David Adeyemi
-- INSERT --

=> added my folder called david-adeyemi

scripts/Yinka-Akinnukawe.js
=> Stage 2 task

scripts/Adedeji-Abiola.js
There was a spelling error in my name that I Have fixed. The script is still passing.
=> fixed error in my name spelling

scripts/Ifunanya-Nwankwo.js
I have finished up, Locally I have no issues but if there is error, let me know. Thanks
=> Ifunanya-Nwankwo javascript file commit

scripts/Njie-Frieda.py
In case of any issue, please contact me via @Frieda on slack.
Thanks
=> Task2 under team-incredible completed

scripts/Abdulrahman-Olagunju.js
=> Modify BodeRahman script

scripts/Chibuike-Umechukwu.js
hey, i couldnt test my script because xampp said there is an error somewhere but i am sending my merge anyways
=> added Chibuike-Umechukwu.js file to the scripts folder

scripts/Oluwaseun-Sofoluwe.js
Updated scripts folder with my own script.
=> Added Oluwaseun-Sofoluwe.js

scripts/Callistus-Enekhaze.php
Added the . to my string output
=> Edited my string

scripts/Parth-Pandya.py
Done with the recent task assigned! I'm Great to go ahead!
=> Task-0 @ Team-Incredible

scripts/Aniebiet-Aaron.js
#TEAM-INCREDIBLE 
Great Job @ Leads
=> added Aniebiet-Aaron.js to scripts dir

scripts/Foluso-Kayode.js
This is my script. Well done Team!
=> add full stop

scripts/dare-oduwole.js
=> dare-oduwole's script

scripts/emmanuel-ovurevu.php
I created my script file. Please Merge
=> Emmanuel Ovurevu created his script file

scripts/Adelakun-Wasiu.js
=> my file submission

scripts/Oluwatimilehin-Bello.js
I'm done with the Task, now adding script
=> Adding my script for stage 2

scripts/Oluwakayode-Fadoju.js
=> Initial commit

scripts/eadortsu.php
Added my script  Eugene Adortsu
Hello World, this is Eugene Adortsu with HNGi7 ID HNG-01429 and email mail@eadortsu.com using PHP for stage 2 task.
=> eadortsu.php

scripts/Imeobong-Akpan.php
=> Imeobong-Akpan Script

scripts/Oscar-Ekeyekwu.js
I have been to complete the task of adding my own script to the SCRIPTS directory
=> Task Completed

scripts/Akinsola-Olawoagbo.js
=> Adding my stage 2 task for Team-Incredible

scripts/Ereyomi-Oluwaseyi.php
=> feat: added ereyomi script

scripts/Chukwuemeka-Samuel.py
=> Chukwuemeka-Samuel.py

scripts/omotola-ogundare.js
=> details for new team

scripts/Christian-Chiemela.js
This is my script. Christian Chiemela HNG-04017
=> Christian Chiemela.js

scripts/mutiyah-muritala.js
=> This is my script,Slack ID:U0150G13TED

scripts/Simeon-Udoh.js
Added my script file correctly to the `scripts` folder.
=> Added my script to scripts folder

scripts/Adenuga-Adesanya.js, scripts/Adenuga-Adesanya.js.js
File name corrected, please merge.
=> Adesanya script

scripts/Oyindamilola-Bakare.js
=> Bakare Oyindamola Js

scripts/Lamin-Minteh.py
Lamin Minteh is say HELLO to Team-Incredible
=> Lamin Minteh

scripts/Oluwakayode-Fadoju.js
=> Made adjustments

scripts/Abdullah-Momoh.php
Here's my script addition. Thanks.
=> Add Script for Abdullah Momoh

scripts/Aderoju-Adewale.js
=> Aderoju-Adewale.js

scripts/Michael-Olatunji.js
=> Adding my script

scripts/kipyegon-mercy.php
This is my task one for stage 2 Team incredible, feel free to comment.
=> Task for stage 2 team incredible

scripts/Aniebiet-Aaron.js
Please merge - case sensitivity issue resolved
=> Updated Aniebiet-Aaron.js

scripts/Moronfolu.Olufunke.js
=> chore:added script for intern 00809

scripts/Francis-Obadiah.js
=> my first task check in team incredible

scripts/onengiye-richard.py
=> Add introduction

scripts/Amarachi-Erem.py
Removed the formatted strings from my python file
=> Removed the formatted strings from my python file

scripts/Simeon-Udoh.js
This pr is in regard to the recommendation on PR https://github.com/elishaukpong/Team-Incredible/pull/444
=> updated my script to meet the requirement

scripts/gideon-peters.js
The former email was the wrong one
=> Corrected email

scripts/Onengiye-Amadi.js
HNGi7-03279
Onengiye-Amadi Script
=> Onengiye-Amadi Script

scripts/Anuoluwapo-Oderinlo.php
I Anuoluwapo(slack name) added a script in php
=> Anuoluwapo

scripts/oluwafemi-ogundipe.js
=> nameing pathern changed

scripts/Dolapo-Balogun.js
=> Dolapo-Balogun script

scripts/ahmed-khaled.js
=> adding task

scripts/mikail-rasheed.js
Kindly check and dm @AALOLE on slack
=> script updated

scripts/Golden-Idikibiebuma.py
I added Golden.Idikibiebuma.py to the script folder
=> Added Golden-Idikibiebuma.py

scripts/Blessing-Uduose.py
=> Efosa updated

scripts/mikail-rasheed.js
full stop added. console.log before and returning the output.
=> updated aalole script

scripts/ONIFADE-BOLUWATIFE.py
=> ONIFADE BOLUwATIFE BASIT"

scripts/mercy-Godwin.py
if my code current code isn't working please merge if not close
=> Esi_python2

scripts/Stephen-Ilori.php
My Pull Request. Hope I am not late
=> Ilori Stephen Initial Commit

scripts/Olayiwola-Ayoola.php
=> Created Olayiwola-Ayoola.php

scripts/Makinde-Tolu.php
=> tolu makinde file

scripts/Moronfolu.Olufunke.js
=> chore:updated intern 00809 script

scripts/Stephen-Chukwuma.js
Stephen's task to team-incredible assignment
=> Stvyn task

scripts/Opeyemi-Adeniji.js
=> Opeyemi-Adeniji script

scripts/olatunde-olanipekun.php
=> submission of orlawealth script for approval

scripts/george-owoicho.py
=> Added my script george-owoicho.py

emeruwa-ijeoma.js, scripts/ijeomae.js
=> This is my script, HNG 00463

.gitignore, scripts/Urchy_project.js
my team incredible project using javascript
=> Urchylis hng project

scripts/dave-ok.js
=> Add hello world script

scripts/Derek-Orodu.py
=> chore: Derek Script
